---
blank_issues_enabled: false
contact_links:
  - name: AzureDevOpsBackupTool Community Support
    url: https://github.com/michaelmsonne/AzureDevOpsBackupTool/discussions
    about: Please ask and answer questions here.
